before:
  hooks:
    - make tidy
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    ldflags:
      - -s -w -X github.com/akymos/ff/internal.version={{.Version}} -X github.com/akymos/ff/internal.commit={{.Commit}} -X github.com/akymos/ff/internal.date={{.Date}}
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      386: i386
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
release:
  prerelease: auto
