name: goreleaser

on:
  push:
    branches:
      - main
    tags:
      - '*'

permissions:
  contents: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Install Packages
        run: |
          apt-get -qqy update
          apt-get -qqy install build-essential curl git > /dev/null
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Fetch all tags
        run: git fetch --force --tags
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v3
        with:
          distribution: goreleaser
          version: latest
          args: release --rm-dist
        env:
          GO386: softfloat
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}